version = 1

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "black"

[[transformers]]
name = "google-java-format"